default_context:
  name: "fluxml"
  version: "0.1.0"
  slug: "fluxml"
  command: "fluxml"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "Flux Balance Analysis using Machine Learning"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "flux balance analysis machine learning"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "fluxml"
  docker_service_username: "achillesrasquinha@gmail.com"
  docker_service_reponame: "fluxml"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/fluxml"